---
openapi: 3.0.1
info:
  title: Backend PopMenu API
  version: v1
paths:
  "/api/v1/restaurants/{restaurant_id}/menus/{menu_id}/menu_items":
    get:
      summary: Loads all menu items
      tags:
      - Menu Items
      parameters:
      - name: menu_id
        in: path
        required: true
        schema:
          type: string
      - name: restaurant_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Menu items loaded
          content:
            application/json:
              example:
                data:
                - id: 1
                  name: Menu Item 1
                  price: "$71.67"
                  createdAt: '2025-10-02T22:37:28.531Z'
                  updatedAt: '2025-10-02T22:37:28.531Z'
                - id: 2
                  name: Menu Item 2
                  price: "$74.12"
                  createdAt: '2025-10-02T22:37:28.534Z'
                  updatedAt: '2025-10-02T22:37:28.534Z'
                - id: 3
                  name: Menu Item 3
                  price: "$96.73"
                  createdAt: '2025-10-02T22:37:28.537Z'
                  updatedAt: '2025-10-02T22:37:28.537Z'
                - id: 4
                  name: Menu Item 4
                  price: "$78.34"
                  createdAt: '2025-10-02T22:37:28.539Z'
                  updatedAt: '2025-10-02T22:37:28.539Z'
                - id: 5
                  name: Menu Item 5
                  price: "$14.72"
                  createdAt: '2025-10-02T22:37:28.545Z'
                  updatedAt: '2025-10-02T22:37:28.545Z'
                - id: 6
                  name: Menu Item 6
                  price: "$60.19"
                  createdAt: '2025-10-02T22:37:28.546Z'
                  updatedAt: '2025-10-02T22:37:28.546Z'
                - id: 7
                  name: Menu Item 7
                  price: "$35.76"
                  createdAt: '2025-10-02T22:37:28.547Z'
                  updatedAt: '2025-10-02T22:37:28.547Z'
                - id: 8
                  name: Menu Item 8
                  price: "$83.79"
                  createdAt: '2025-10-02T22:37:28.552Z'
                  updatedAt: '2025-10-02T22:37:28.552Z'
                - id: 9
                  name: Menu Item 9
                  price: "$58.26"
                  createdAt: '2025-10-02T22:37:28.555Z'
                  updatedAt: '2025-10-02T22:37:28.555Z'
                - id: 10
                  name: Menu Item 10
                  price: "$36.95"
                  createdAt: '2025-10-02T22:37:28.557Z'
                  updatedAt: '2025-10-02T22:37:28.557Z'
                meta:
                  currentPage: 1
                  totalPages: 2
                  totalCount: 12
        '404':
          description: Menu or restaurant not found
  "/api/v1/restaurants/{restaurant_id}/menus":
    get:
      summary: Loads all menus
      tags:
      - Menus
      parameters:
      - name: restaurant_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Menus loaded
          content:
            application/json:
              example:
                data:
                - id: 1
                  name: dolore
                  createdAt: '2025-10-02T22:37:28.667Z'
                  updatedAt: '2025-10-02T22:37:28.667Z'
                meta:
                  currentPage: 1
                  totalPages: 1
                  totalCount: 1
  "/api/v1/restaurants/{restaurant_id}/menus/{id}":
    get:
      summary: Loads a menu
      tags:
      - Menus
      security:
      - Bearer: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: restaurant_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Menu loaded
          content:
            application/json:
              example:
                menu:
                  id: 1
                  name: sit
                  createdAt: '2025-10-02T22:37:28.716Z'
                  updatedAt: '2025-10-02T22:37:28.716Z'
                  description: Aliquam ratione ut temporibus.
        '404':
          description: Menu not found
