---
openapi: 3.0.1
info:
  title: Backend PopMenu API
  version: v1
paths:
  "/api/v1/menu_imports":
    post:
      summary: Creates a menu import
      tags:
      - Menu Imports
      parameters: []
      responses:
        '200':
          description: Menu import created
          content:
            application/json:
              example:
              - status: success
                message: 'Menu item created: Burger'
                errors:
              - status: success
                message: 'Menu item created: Small Salad'
                errors:
              - status: success
                message: 'Menu item created: Burger'
                errors:
              - status: success
                message: 'Menu item created: Large Salad'
                errors:
              - status: success
                message: 'Menu item created: Chicken Wings'
                errors:
              - status: error
                message: 'Menu item not created: Burger'
                errors:
                - Name has already been taken
              - status: success
                message: 'Menu item created: Chicken Wings'
                errors:
              - status: success
                message: 'Menu item created: Mega "Burger"'
                errors:
              - status: success
                message: 'Menu item created: Lobster Mac & Cheese'
                errors:
        '422':
          description: Menu import not created
          content:
            application/json:
              example:
                errors:
                  file_path:
                  - must be a valid file type
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: file
  "/api/v1/restaurants/{restaurant_id}/menus/{menu_id}/menu_items":
    get:
      summary: Loads all menu items
      tags:
      - Menu Items
      parameters:
      - name: menu_id
        in: path
        required: true
        schema:
          type: string
      - name: restaurant_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Menu items loaded
          content:
            application/json:
              example:
                data:
                - id: 1
                  name: Menu Item 1
                  price: 771.0
                  priceFormatted: "$771.00"
                  createdAt: '2025-10-08T00:47:29.097Z'
                  updatedAt: '2025-10-08T00:47:29.097Z'
                - id: 2
                  name: Menu Item 2
                  price: 563.0
                  priceFormatted: "$563.00"
                  createdAt: '2025-10-08T00:47:29.102Z'
                  updatedAt: '2025-10-08T00:47:29.102Z'
                - id: 3
                  name: Menu Item 3
                  price: 779.0
                  priceFormatted: "$779.00"
                  createdAt: '2025-10-08T00:47:29.105Z'
                  updatedAt: '2025-10-08T00:47:29.105Z'
                - id: 4
                  name: Menu Item 4
                  price: 252.0
                  priceFormatted: "$252.00"
                  createdAt: '2025-10-08T00:47:29.114Z'
                  updatedAt: '2025-10-08T00:47:29.114Z'
                - id: 5
                  name: Menu Item 5
                  price: 399.0
                  priceFormatted: "$399.00"
                  createdAt: '2025-10-08T00:47:29.116Z'
                  updatedAt: '2025-10-08T00:47:29.116Z'
                - id: 6
                  name: Menu Item 6
                  price: 243.0
                  priceFormatted: "$243.00"
                  createdAt: '2025-10-08T00:47:29.120Z'
                  updatedAt: '2025-10-08T00:47:29.120Z'
                - id: 7
                  name: Menu Item 7
                  price: 260.0
                  priceFormatted: "$260.00"
                  createdAt: '2025-10-08T00:47:29.124Z'
                  updatedAt: '2025-10-08T00:47:29.124Z'
                - id: 8
                  name: Menu Item 8
                  price: 583.0
                  priceFormatted: "$583.00"
                  createdAt: '2025-10-08T00:47:29.129Z'
                  updatedAt: '2025-10-08T00:47:29.129Z'
                - id: 9
                  name: Menu Item 9
                  price: 823.0
                  priceFormatted: "$823.00"
                  createdAt: '2025-10-08T00:47:29.132Z'
                  updatedAt: '2025-10-08T00:47:29.132Z'
                - id: 10
                  name: Menu Item 10
                  price: 504.0
                  priceFormatted: "$504.00"
                  createdAt: '2025-10-08T00:47:29.134Z'
                  updatedAt: '2025-10-08T00:47:29.134Z'
                meta:
                  currentPage: 1
                  totalPages: 2
                  totalCount: 12
        '404':
          description: Menu or restaurant not found
  "/api/v1/restaurants/{restaurant_id}/menus":
    get:
      summary: Loads all menus
      tags:
      - Menus
      parameters:
      - name: restaurant_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Menus loaded
          content:
            application/json:
              example:
                data:
                - id: 1
                  name: inventore
                  createdAt: '2025-10-08T00:47:29.255Z'
                  updatedAt: '2025-10-08T00:47:29.255Z'
                meta:
                  currentPage: 1
                  totalPages: 1
                  totalCount: 1
  "/api/v1/restaurants/{restaurant_id}/menus/{id}":
    get:
      summary: Loads a menu
      tags:
      - Menus
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: restaurant_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Menu loaded
          content:
            application/json:
              example:
                menu:
                  id: 1
                  name: a
                  createdAt: '2025-10-08T00:47:29.312Z'
                  updatedAt: '2025-10-08T00:47:29.312Z'
                  description: Nobis dolore placeat magnam.
        '404':
          description: Menu not found
  "/api/v1/restaurants":
    get:
      summary: Loads all restaurants
      tags:
      - Restaurants
      responses:
        '200':
          description: Restaurants loaded
          content:
            application/json:
              example:
                data:
                - id: 1
                  name: quia
                  createdAt: '2025-10-08T00:47:29.341Z'
                  updatedAt: '2025-10-08T00:47:29.341Z'
                - id: 2
                  name: voluptas
                  createdAt: '2025-10-08T00:47:29.342Z'
                  updatedAt: '2025-10-08T00:47:29.342Z'
                - id: 3
                  name: aut
                  createdAt: '2025-10-08T00:47:29.343Z'
                  updatedAt: '2025-10-08T00:47:29.343Z'
                - id: 4
                  name: sed
                  createdAt: '2025-10-08T00:47:29.344Z'
                  updatedAt: '2025-10-08T00:47:29.344Z'
                - id: 5
                  name: nulla
                  createdAt: '2025-10-08T00:47:29.344Z'
                  updatedAt: '2025-10-08T00:47:29.344Z'
                - id: 6
                  name: qui
                  createdAt: '2025-10-08T00:47:29.346Z'
                  updatedAt: '2025-10-08T00:47:29.346Z'
                - id: 7
                  name: et
                  createdAt: '2025-10-08T00:47:29.347Z'
                  updatedAt: '2025-10-08T00:47:29.347Z'
                - id: 8
                  name: ea
                  createdAt: '2025-10-08T00:47:29.350Z'
                  updatedAt: '2025-10-08T00:47:29.350Z'
                - id: 9
                  name: distinctio
                  createdAt: '2025-10-08T00:47:29.353Z'
                  updatedAt: '2025-10-08T00:47:29.353Z'
                - id: 10
                  name: rerum
                  createdAt: '2025-10-08T00:47:29.354Z'
                  updatedAt: '2025-10-08T00:47:29.354Z'
                meta:
                  currentPage: 1
                  totalPages: 2
                  totalCount: 12
    post:
      summary: Creates a restaurant
      tags:
      - Restaurants
      parameters: []
      responses:
        '201':
          description: Restaurant created
          content:
            application/json:
              example:
                restaurant:
                  id: 1
                  name: ea
                  createdAt: '2025-10-08T00:47:29.371Z'
                  updatedAt: '2025-10-08T00:47:29.371Z'
                  description: Sunt amet cum consectetur.
        '422':
          description: Restaurant not created
          content:
            application/json:
              example:
                errors:
                  name:
                  - can't be blank
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: consequatur
                description:
                  type: string
                  example: Ea sit quasi repudiandae.
  "/api/v1/restaurants/{id}":
    get:
      summary: Loads a restaurant
      tags:
      - Restaurants
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Restaurant loaded
          content:
            application/json:
              example:
                restaurant:
                  id: 1
                  name: nihil
                  createdAt: '2025-10-08T00:47:29.390Z'
                  updatedAt: '2025-10-08T00:47:29.390Z'
                  description: Autem dolorem blanditiis minus.
        '404':
          description: Restaurant not found
    put:
      summary: Updates a restaurant
      tags:
      - Restaurants
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Restaurant updated
          content:
            application/json:
              example:
                restaurant:
                  id: 1
                  name: atque
                  createdAt: '2025-10-08T00:47:29.406Z'
                  updatedAt: '2025-10-08T00:47:29.411Z'
                  description: Aliquid dolorem laudantium odio.
        '404':
          description: Restaurant not found
        '422':
          description: Restaurant not updated
          content:
            application/json:
              example:
                errors:
                  name:
                  - can't be blank
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: sit
                description:
                  type: string
                  example: Nulla veritatis nobis possimus.
    delete:
      summary: Deletes a restaurant
      tags:
      - Restaurants
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '204':
          description: Restaurant deleted
        '404':
          description: Restaurant not found
