---
openapi: 3.0.1
info:
  title: Backend PopMenu API
  version: v1
paths:
  "/api/v1/menu_imports":
    post:
      summary: Creates a menu import
      tags:
      - Menu Imports
      parameters: []
      responses:
        '200':
          description: Menu import created
          content:
            application/json:
              example:
              - status: success
                message: 'Menu item created: Burger'
                errors:
              - status: success
                message: 'Menu item created: Small Salad'
                errors:
              - status: error
                message: 'Menu item not created: Burger'
                errors:
                - Name has already been taken
              - status: success
                message: 'Menu item created: Large Salad'
                errors:
              - status: success
                message: 'Menu item created: Chicken Wings'
                errors:
              - status: error
                message: 'Menu item not created: Burger'
                errors:
                - Name has already been taken
              - status: error
                message: 'Menu item not created: Chicken Wings'
                errors:
                - Name has already been taken
              - status: success
                message: 'Menu item created: Mega "Burger"'
                errors:
              - status: success
                message: 'Menu item created: Lobster Mac & Cheese'
                errors:
        '422':
          description: Menu import not created
          content:
            application/json:
              example:
                errors:
                  file_path:
                  - must be a valid file type
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: file
  "/api/v1/restaurants/{restaurant_id}/menus/{menu_id}/menu_items":
    get:
      summary: Loads all menu items
      tags:
      - Menu Items
      parameters:
      - name: menu_id
        in: path
        required: true
        schema:
          type: string
      - name: restaurant_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Menu items loaded
          content:
            application/json:
              example:
                data:
                - id: 1
                  name: Menu Item 1
                  price: "$32.76"
                  createdAt: '2025-10-07T23:49:53.295Z'
                  updatedAt: '2025-10-07T23:49:53.295Z'
                - id: 2
                  name: Menu Item 2
                  price: "$57.49"
                  createdAt: '2025-10-07T23:49:53.299Z'
                  updatedAt: '2025-10-07T23:49:53.299Z'
                - id: 3
                  name: Menu Item 3
                  price: "$68.44"
                  createdAt: '2025-10-07T23:49:53.301Z'
                  updatedAt: '2025-10-07T23:49:53.301Z'
                - id: 4
                  name: Menu Item 4
                  price: "$99.53"
                  createdAt: '2025-10-07T23:49:53.304Z'
                  updatedAt: '2025-10-07T23:49:53.304Z'
                - id: 5
                  name: Menu Item 5
                  price: "$59.31"
                  createdAt: '2025-10-07T23:49:53.310Z'
                  updatedAt: '2025-10-07T23:49:53.310Z'
                - id: 6
                  name: Menu Item 6
                  price: "$38.36"
                  createdAt: '2025-10-07T23:49:53.315Z'
                  updatedAt: '2025-10-07T23:49:53.315Z'
                - id: 7
                  name: Menu Item 7
                  price: "$95.24"
                  createdAt: '2025-10-07T23:49:53.317Z'
                  updatedAt: '2025-10-07T23:49:53.317Z'
                - id: 8
                  name: Menu Item 8
                  price: "$74.51"
                  createdAt: '2025-10-07T23:49:53.328Z'
                  updatedAt: '2025-10-07T23:49:53.328Z'
                - id: 9
                  name: Menu Item 9
                  price: "$41.96"
                  createdAt: '2025-10-07T23:49:53.332Z'
                  updatedAt: '2025-10-07T23:49:53.332Z'
                - id: 10
                  name: Menu Item 10
                  price: "$34.05"
                  createdAt: '2025-10-07T23:49:53.336Z'
                  updatedAt: '2025-10-07T23:49:53.336Z'
                meta:
                  currentPage: 1
                  totalPages: 2
                  totalCount: 12
        '404':
          description: Menu or restaurant not found
  "/api/v1/restaurants/{restaurant_id}/menus":
    get:
      summary: Loads all menus
      tags:
      - Menus
      parameters:
      - name: restaurant_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Menus loaded
          content:
            application/json:
              example:
                data:
                - id: 1
                  name: itaque
                  createdAt: '2025-10-07T23:49:53.425Z'
                  updatedAt: '2025-10-07T23:49:53.425Z'
                meta:
                  currentPage: 1
                  totalPages: 1
                  totalCount: 1
  "/api/v1/restaurants/{restaurant_id}/menus/{id}":
    get:
      summary: Loads a menu
      tags:
      - Menus
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: restaurant_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Menu loaded
          content:
            application/json:
              example:
                menu:
                  id: 1
                  name: eligendi
                  createdAt: '2025-10-07T23:49:53.483Z'
                  updatedAt: '2025-10-07T23:49:53.483Z'
                  description: Expedita repellendus laborum dolor.
        '404':
          description: Menu not found
  "/api/v1/restaurants":
    get:
      summary: Loads all restaurants
      tags:
      - Restaurants
      responses:
        '200':
          description: Restaurants loaded
          content:
            application/json:
              example:
                data:
                - id: 1
                  name: accusantium
                  createdAt: '2025-10-07T23:49:53.520Z'
                  updatedAt: '2025-10-07T23:49:53.520Z'
                - id: 2
                  name: et
                  createdAt: '2025-10-07T23:49:53.521Z'
                  updatedAt: '2025-10-07T23:49:53.521Z'
                - id: 3
                  name: animi
                  createdAt: '2025-10-07T23:49:53.522Z'
                  updatedAt: '2025-10-07T23:49:53.522Z'
                - id: 4
                  name: et
                  createdAt: '2025-10-07T23:49:53.525Z'
                  updatedAt: '2025-10-07T23:49:53.525Z'
                - id: 5
                  name: aliquam
                  createdAt: '2025-10-07T23:49:53.527Z'
                  updatedAt: '2025-10-07T23:49:53.527Z'
                - id: 6
                  name: excepturi
                  createdAt: '2025-10-07T23:49:53.529Z'
                  updatedAt: '2025-10-07T23:49:53.529Z'
                - id: 7
                  name: et
                  createdAt: '2025-10-07T23:49:53.531Z'
                  updatedAt: '2025-10-07T23:49:53.531Z'
                - id: 8
                  name: commodi
                  createdAt: '2025-10-07T23:49:53.536Z'
                  updatedAt: '2025-10-07T23:49:53.536Z'
                - id: 9
                  name: distinctio
                  createdAt: '2025-10-07T23:49:53.542Z'
                  updatedAt: '2025-10-07T23:49:53.542Z'
                - id: 10
                  name: ut
                  createdAt: '2025-10-07T23:49:53.543Z'
                  updatedAt: '2025-10-07T23:49:53.543Z'
                meta:
                  currentPage: 1
                  totalPages: 2
                  totalCount: 12
    post:
      summary: Creates a restaurant
      tags:
      - Restaurants
      parameters: []
      responses:
        '201':
          description: Restaurant created
          content:
            application/json:
              example:
                restaurant:
                  id: 1
                  name: possimus
                  createdAt: '2025-10-07T23:49:53.571Z'
                  updatedAt: '2025-10-07T23:49:53.571Z'
                  description: Non fugit excepturi ad.
        '422':
          description: Restaurant not created
          content:
            application/json:
              example:
                errors:
                  name:
                  - can't be blank
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: voluptatem
                description:
                  type: string
                  example: Et officia ut est.
  "/api/v1/restaurants/{id}":
    get:
      summary: Loads a restaurant
      tags:
      - Restaurants
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Restaurant loaded
          content:
            application/json:
              example:
                restaurant:
                  id: 1
                  name: qui
                  createdAt: '2025-10-07T23:49:53.597Z'
                  updatedAt: '2025-10-07T23:49:53.597Z'
                  description: Voluptas recusandae accusamus id.
        '404':
          description: Restaurant not found
    put:
      summary: Updates a restaurant
      tags:
      - Restaurants
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Restaurant updated
          content:
            application/json:
              example:
                restaurant:
                  id: 1
                  name: quaerat
                  createdAt: '2025-10-07T23:49:53.612Z'
                  updatedAt: '2025-10-07T23:49:53.617Z'
                  description: Vel sit voluptates mollitia.
        '404':
          description: Restaurant not found
        '422':
          description: Restaurant not updated
          content:
            application/json:
              example:
                errors:
                  name:
                  - can't be blank
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: quas
                description:
                  type: string
                  example: Consequatur tempora aperiam recusandae.
    delete:
      summary: Deletes a restaurant
      tags:
      - Restaurants
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '204':
          description: Restaurant deleted
        '404':
          description: Restaurant not found
