---
openapi: 3.0.1
info:
  title: Backend PopMenu API
  version: v1
paths:
  "/api/v1/menu_imports":
    post:
      summary: Creates a menu import
      tags:
      - Menu Imports
      parameters: []
      responses:
        '200':
          description: Menu import created
          content:
            application/json:
              example:
              - status: success
                message: Burger created and was correctly associated to 'lunch'
                errors:
              - status: success
                message: Small Salad created and was correctly associated to 'lunch'
                errors:
              - status: success
                message: Burger already exists and was correctly associated to 'dinner'
                errors:
              - status: success
                message: Large Salad created and was correctly associated to 'dinner'
                errors:
              - status: success
                message: Chicken Wings created and was correctly associated to 'lunch'
                errors:
              - status: error
                message: Burger not created
                errors:
                - Name has already been taken
              - status: success
                message: Chicken Wings already exists and was correctly associated
                  to 'lunch'
                errors:
              - status: success
                message: Mega "Burger" created and was correctly associated to 'dinner'
                errors:
              - status: success
                message: Lobster Mac & Cheese created and was correctly associated
                  to 'dinner'
                errors:
        '422':
          description: Menu import not created
          content:
            application/json:
              example:
                errors:
                  file_path:
                  - must be a valid file type
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: file
  "/api/v1/restaurants/{restaurant_id}/menus/{menu_id}/menu_items":
    get:
      summary: Loads all menu items
      tags:
      - Menu Items
      parameters:
      - name: menu_id
        in: path
        required: true
        schema:
          type: string
      - name: restaurant_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Menu items loaded
          content:
            application/json:
              example:
                data:
                - id: 1
                  name: Menu Item 1
                  price: 292.0
                  priceFormatted: "$292.00"
                  createdAt: '2025-10-08T01:03:52.424Z'
                  updatedAt: '2025-10-08T01:03:52.424Z'
                - id: 2
                  name: Menu Item 2
                  price: 688.0
                  priceFormatted: "$688.00"
                  createdAt: '2025-10-08T01:03:52.426Z'
                  updatedAt: '2025-10-08T01:03:52.426Z'
                - id: 3
                  name: Menu Item 3
                  price: 287.0
                  priceFormatted: "$287.00"
                  createdAt: '2025-10-08T01:03:52.428Z'
                  updatedAt: '2025-10-08T01:03:52.428Z'
                - id: 4
                  name: Menu Item 4
                  price: 739.0
                  priceFormatted: "$739.00"
                  createdAt: '2025-10-08T01:03:52.433Z'
                  updatedAt: '2025-10-08T01:03:52.433Z'
                - id: 5
                  name: Menu Item 5
                  price: 687.0
                  priceFormatted: "$687.00"
                  createdAt: '2025-10-08T01:03:52.435Z'
                  updatedAt: '2025-10-08T01:03:52.435Z'
                - id: 6
                  name: Menu Item 6
                  price: 717.0
                  priceFormatted: "$717.00"
                  createdAt: '2025-10-08T01:03:52.437Z'
                  updatedAt: '2025-10-08T01:03:52.437Z'
                - id: 7
                  name: Menu Item 7
                  price: 896.0
                  priceFormatted: "$896.00"
                  createdAt: '2025-10-08T01:03:52.440Z'
                  updatedAt: '2025-10-08T01:03:52.440Z'
                - id: 8
                  name: Menu Item 8
                  price: 914.0
                  priceFormatted: "$914.00"
                  createdAt: '2025-10-08T01:03:52.444Z'
                  updatedAt: '2025-10-08T01:03:52.444Z'
                - id: 9
                  name: Menu Item 9
                  price: 688.0
                  priceFormatted: "$688.00"
                  createdAt: '2025-10-08T01:03:52.445Z'
                  updatedAt: '2025-10-08T01:03:52.445Z'
                - id: 10
                  name: Menu Item 10
                  price: 592.0
                  priceFormatted: "$592.00"
                  createdAt: '2025-10-08T01:03:52.447Z'
                  updatedAt: '2025-10-08T01:03:52.447Z'
                meta:
                  currentPage: 1
                  totalPages: 2
                  totalCount: 12
        '404':
          description: Menu or restaurant not found
  "/api/v1/restaurants/{restaurant_id}/menus":
    get:
      summary: Loads all menus
      tags:
      - Menus
      parameters:
      - name: restaurant_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Menus loaded
          content:
            application/json:
              example:
                data:
                - id: 1
                  name: consectetur
                  createdAt: '2025-10-08T01:03:52.564Z'
                  updatedAt: '2025-10-08T01:03:52.564Z'
                meta:
                  currentPage: 1
                  totalPages: 1
                  totalCount: 1
  "/api/v1/restaurants/{restaurant_id}/menus/{id}":
    get:
      summary: Loads a menu
      tags:
      - Menus
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: restaurant_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Menu loaded
          content:
            application/json:
              example:
                menu:
                  id: 1
                  name: sed
                  createdAt: '2025-10-08T01:03:52.623Z'
                  updatedAt: '2025-10-08T01:03:52.623Z'
                  description: Commodi sit sed necessitatibus.
        '404':
          description: Menu not found
  "/api/v1/restaurants":
    get:
      summary: Loads all restaurants
      tags:
      - Restaurants
      responses:
        '200':
          description: Restaurants loaded
          content:
            application/json:
              example:
                data:
                - id: 1
                  name: non
                  createdAt: '2025-10-08T01:03:52.652Z'
                  updatedAt: '2025-10-08T01:03:52.652Z'
                - id: 2
                  name: impedit
                  createdAt: '2025-10-08T01:03:52.654Z'
                  updatedAt: '2025-10-08T01:03:52.654Z'
                - id: 3
                  name: magnam
                  createdAt: '2025-10-08T01:03:52.654Z'
                  updatedAt: '2025-10-08T01:03:52.654Z'
                - id: 4
                  name: dolorem
                  createdAt: '2025-10-08T01:03:52.655Z'
                  updatedAt: '2025-10-08T01:03:52.655Z'
                - id: 5
                  name: quia
                  createdAt: '2025-10-08T01:03:52.656Z'
                  updatedAt: '2025-10-08T01:03:52.656Z'
                - id: 6
                  name: voluptates
                  createdAt: '2025-10-08T01:03:52.657Z'
                  updatedAt: '2025-10-08T01:03:52.657Z'
                - id: 7
                  name: minus
                  createdAt: '2025-10-08T01:03:52.659Z'
                  updatedAt: '2025-10-08T01:03:52.659Z'
                - id: 8
                  name: dolores
                  createdAt: '2025-10-08T01:03:52.662Z'
                  updatedAt: '2025-10-08T01:03:52.662Z'
                - id: 9
                  name: voluptatibus
                  createdAt: '2025-10-08T01:03:52.665Z'
                  updatedAt: '2025-10-08T01:03:52.665Z'
                - id: 10
                  name: dolorum
                  createdAt: '2025-10-08T01:03:52.666Z'
                  updatedAt: '2025-10-08T01:03:52.666Z'
                meta:
                  currentPage: 1
                  totalPages: 2
                  totalCount: 12
    post:
      summary: Creates a restaurant
      tags:
      - Restaurants
      parameters: []
      responses:
        '201':
          description: Restaurant created
          content:
            application/json:
              example:
                restaurant:
                  id: 1
                  name: ut
                  createdAt: '2025-10-08T01:03:52.685Z'
                  updatedAt: '2025-10-08T01:03:52.685Z'
                  description: Dolorem ea nam ut.
        '422':
          description: Restaurant not created
          content:
            application/json:
              example:
                errors:
                  name:
                  - can't be blank
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: distinctio
                description:
                  type: string
                  example: Perferendis fugiat accusamus necessitatibus.
  "/api/v1/restaurants/{id}":
    get:
      summary: Loads a restaurant
      tags:
      - Restaurants
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Restaurant loaded
          content:
            application/json:
              example:
                restaurant:
                  id: 1
                  name: est
                  createdAt: '2025-10-08T01:03:52.706Z'
                  updatedAt: '2025-10-08T01:03:52.706Z'
                  description: Quisquam sapiente non soluta.
        '404':
          description: Restaurant not found
    put:
      summary: Updates a restaurant
      tags:
      - Restaurants
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Restaurant updated
          content:
            application/json:
              example:
                restaurant:
                  id: 1
                  name: nesciunt
                  createdAt: '2025-10-08T01:03:52.719Z'
                  updatedAt: '2025-10-08T01:03:52.722Z'
                  description: Aliquam consectetur laudantium quia.
        '404':
          description: Restaurant not found
        '422':
          description: Restaurant not updated
          content:
            application/json:
              example:
                errors:
                  name:
                  - can't be blank
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: omnis
                description:
                  type: string
                  example: Explicabo est aut quod.
    delete:
      summary: Deletes a restaurant
      tags:
      - Restaurants
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '204':
          description: Restaurant deleted
        '404':
          description: Restaurant not found
